"""añadir_campo_es_admin

Revision ID: 4b325e749368
Revises: bfa89173b56a
Create Date: 2026-05-20 21:32:37.198664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b325e749368'
down_revision: Union[str, Sequence[str], None] = 'bfa89173b56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Añade la columna como nullable primero
    op.add_column('usuarios', sa.Column('es_admin', sa.Boolean(), nullable=True))
    # Establece false por defecto para los existentes
    op.execute('UPDATE usuarios SET es_admin = false')
    # Ahora la hace NOT NULL
    op.alter_column('usuarios', 'es_admin', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'es_admin')
    op.create_table('recurrentes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('frecuencia', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('dia_repeticion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('proxima_ejecucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cuenta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], name=op.f('recurrentes_id_categoria_fkey')),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], name=op.f('recurrentes_id_cuenta_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('recurrentes_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurrentes_pkey'))
    )
    op.create_index(op.f('ix_recurrentes_id'), 'recurrentes', ['id'], unique=False)
    # ### end Alembic commands ###
