"""añadir_tabla_desgloses_transaccion

Revision ID: 89ce68351810
Revises: 4b325e749368
Create Date: 2026-05-21 15:09:10.854283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89ce68351810'
down_revision: Union[str, Sequence[str], None] = '4b325e749368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurrentes_id'), table_name='recurrentes')
    op.drop_table('recurrentes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrentes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('frecuencia', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('dia_repeticion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('proxima_ejecucion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_cuenta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], name=op.f('recurrentes_id_categoria_fkey')),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], name=op.f('recurrentes_id_cuenta_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('recurrentes_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurrentes_pkey'))
    )
    op.create_index(op.f('ix_recurrentes_id'), 'recurrentes', ['id'], unique=False)
    # ### end Alembic commands ###
